### ISSUE TITLE
no module named celery.signals 

### ISSUE THREAD

**Issue by essymanyeki16** [qlands/FormShare#15]
Dear Carlos,

I have this error when i run python manage.py validate. First the error was django.core.management after installing django, this is the error i got. 
![virtualbox_data collector_26_03_2018_11_35_46](https://user-images.githubusercontent.com/17991968/37895532-3d67367a-30ea-11e8-8b4d-cdb7941d6529.png)

Thank you

**Comment by qlands** [comment]
Hi I am closing this because FormShare 2.0 has been released. 1.0 is no longer maintained.

I can help you migrate your FormShare 1.0 data to FormShare 2.0
