### ISSUE TITLE
ViewDoesNotExist at /

### ISSUE THREAD

**Issue by riiko** [qlands/FormShare#16]
I managed to install and runserver but I am getting the below error while trying to logout.

_Could not import formshare.apps.main.registration_views.LogoutView. View does not exist in module formshare.apps.main.registration_views._

**Comment by qlands** [comment]
Hi,

I am closing this because FormShare 2.0 has been released. 1.0 is no longer maintained.

Please upgrade your FormShare installation to 2.0
