### ISSUE TITLE
DatabaseError: DatabaseWrapper objects created in a thread can only be used in that same thread

### ISSUE THREAD

**Issue by collinsod** [qlands/FormShare#17]
I am unable to export submissions to excel or csv. It keeps saying 'Pending .. Click to refresh' or 'Refreshing'

![image](https://user-images.githubusercontent.com/7247285/65592660-ae5e9280-df97-11e9-949d-8674dced301a.png)

Error.log
self.validate_thread_sharing()
File "/opt/formshare/lib/python2.7/site-packages/django/db/backends/__init__.py", line 499, in validate_thread_sharing
% (self.alias, self._thread_ident, thread.get_ident()))
DatabaseError: DatabaseWrapper objects created in a thread can only be used in that same thread. The object with alias 'default' was created in thread id 139738191816448 and this is thread id 139738242172672.

**Comment by qlands** [comment]
Hi Collins,

That problem is because of old libraries and bad code. I suggest you use FormShare 2.0.

If you have data in 1.0 I can help you migrate it to 2.0.
