### ISSUE TITLE
Internal Server Error when download data in csv format

### ISSUE THREAD

**Issue by NobelIslam** [qlands/FormShare#28]
Hi! When I have click download data in CSV format then msg shown Internal Server error 500. Please request https://github.com/qlands/FormShare. As a result I did not pull data in csv format from odk.

**Comment by qlands** [comment]
Hi.

Does this happen in FormShare.org? or on a custom installation of FormShare?

If you are running FormShare on your computer using Docker, please attach to this issue the file /opt/formshare/log/error_log

**Comment by BioversityCostaRica** [comment]
Hi @NobelIslam . Is this a problem with the IPAS installation of FormShare (MARS)?

**Comment by qlands** [comment]
@NobelIslam . This bug was caused by ODKTools and has been fixed [here](https://github.com/qlands/odktools/commit/5819d10c547de8ef434ea113717d70ae1647a951)
