### ISSUE TITLE
Dynamic form linking in case management?

### ISSUE THREAD

**Issue by bensonik** [qlands/FormShare#47]
Use case creator dataset a media file for a follow-up form?

**Comment by qlands** [comment]
Hi @bensonik 

Can you explain more about this issue?

**Comment by bensonik** [comment]
Hi @qlands , 

1. Follow up form using `select_one_from_file real_time_csv.csv`  requires attachment upload, with no option to access the `real time csv file` generated/updated by formshare from `case creator` form.
2. On `Create or edit the real-time CSV case file` page, the link to download an example real time csv is broken.

**Comment by qlands** [comment]
OK. We will look into it. It seems that we forgot to attach the example.

For now please have a look a this case examples: www.qlands.com/other_files/case_examples.zip
In the examples the ODK "case_follow_up.xlsx" uses a file called households.csv  . This file has the structure: list_name|name|label|distrito_id  and has some test data. distrito_id is used to filter the households per district. 

If you use this examples, after you upload "case_start.xlsx" if you create the "real time CSV file" you can attach "distrito" as "distrito_id". Then after you upload "case_follow_up.xlsx" and upload households.csv to the form (this is the temporary data) FormShare will link "households.csv" to the "real time CSV file". In this way each time that you create a case and then refresh the form "case_follow_up" in ODK Collect it will pull the latest cases.

**Comment by qlands** [comment]
Fixed in commit bded3954d42c7fa4822a89e3ac490f0ceb6d4242 and available in release 2.14.0
