### ISSUE TITLE
Internal Server Error when loading ../odata/users

### ISSUE THREAD

**Issue by bensonik** [qlands/FormShare#54]
Trying to set up OData feed user priviledges, getting 500 error on click ../odata/users

**Comment by qlands** [comment]
Thank you for reporting the issue,

Yes, we wroke the OData plugin in the commit 412a89c197af92f8ce4e82c2e1685888143c1853  . We will fix the OData plugin in the next upgrade planned for 20/July/2022

Sorry for the inconvenience.

**Comment by qlands** [comment]
Hi Benson,

An update on this. We fixed the issue but we are working on a new release 2.17.0 to be ready this week as we are migrating to the newest version of Ubuntu server 22.04 in the docker image.

Sorry for the delay and thank you for using FormShare

**Comment by bensonik** [comment]
Thanks Carlos for the continued support and efforts in always improving FormShare's features and user experience. Much appreciated!  Looking forward to the new release :-) 

Cheers!!!

**Comment by qlands** [comment]
Hi Benson,

We uploaded the fix on the plugin and now you can access the OData settings. 

I checked and all seems to be working fine. Let us know if you face any other problems.
