### ISSUE TITLE
Overwrite Elasticsearch check when using Opensearch?

### ISSUE THREAD

**Issue by poVoq** [qlands/FormShare#64]
I am trying to setup again a small test instance with Opensearch (the FOSS fork of Elasticsearch 7.2), which should be fully compatible with Elasticsearch.

However it seems like Formshare is checking for Elasticsearch specifically as I get this error with the Docker container:

`elasticsearch.exceptions.UnsupportedProductError: The client noticed that the server is not Elasticsearch and we do not support this unknown product`

Given the problematic new licensing of Elasticsearch and that Opensearch is still a fully compatible fork, I think it would be good if this check could be over-written somehow as I assume this is why the container fails to start correctly.

Obviously I am aware that this isn't officially supported.

Thanks.

**Comment by qlands** [comment]
Hi @poVoq 

I appreciate your question. The Elasticsearch library produces that exception. 

The new license of Elasticsearch does not impact applications like FormShare (https://www.elastic.co/pricing/faq/licensing#elasticsearch-backend-how-affect-me)

Therefore the change in License does not affect users using https://formshare.org or users deploying FormShare from source or through Docker.

We have no plans to support OpenSearch. You should use Elasticsearch or Fork and modify the source code to support OpenSearch.
