### ISSUE TITLE
enketo single submit url

### ISSUE THREAD

**Issue by bensonik** [qlands/FormShare#66]
I achieved this by replacing `x` in `https://formshare.org/enketo/x/...` with `single`.  `https://formshare.org/enketo/single/...` works and redirects to the default enketo thanks page.

1. Is there an official method to generate the single submission URL in FormShare?
2. is it possible to have a custom thanks page for a form, for example, to have it in a different language or text?

Cheers Team FormShare!
Benson

**Comment by qlands** [comment]
Hi Benson,

Thank you for your suggestion. The [Enketo plugin](https://github.com/qlands/formshare_enketo_plugin) does not currently perform those actions. But we will update the plugin with you with your suggestions. We expect the new version to be available on Monday, the 14th of August.

**Comment by qlands** [comment]
Hi Benson,

The new version of the plugin is ready and active in [https://formshare.org](https://formshare.org). Just click on "Generate links button" to generate the new tools.

You can read the details here: https://github.com/qlands/formshare_enketo_plugin#use-the-plugin
