### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by bensonik** [qlands/FormShare#67]
[formshare.po.zip](https://github.com/qlands/FormShare/files/12458811/formshare.po.zip)

Base translation done with [translate-po](https://github.com/zcribe/translate-po), then checked through (intermediate German language skills :-) ) so I expect some improvements as higher language skilled users interact with it.

Benson

**Comment by qlands** [comment]
Oh Cool!

Thank you very much! I will add it to the translations.
