### ISSUE TITLE
Empty columns with the suffix '-desc' in Exported Excel Files

### ISSUE THREAD

**Issue by tosmartak** [qlands/FormShare#69]
When exporting data from Formshare, for each of the variables, there are additional empty columns with the **previous variable name + the suffix ‘-desc’** even if you select codes only during download. Although one could drop these empty columns during cleaning since they are empty, but ideally for the sake of the team, this unnecessary columns should not be added unless one generates an Excel report with codes and labels for categorical variables. Currently, there is no option during export to exclude these columns.

I have included a sample of the exported file below, in which I highlighted few of those columns in grey.
[infrastructure_20230910.xlsx](https://github.com/qlands/FormShare/files/12756107/infrastructure_20230910.xlsx)

**Comment by qlands** [comment]
Hi Tosin. 

We updated the servers and now the exports should be OK.

Regards,
The QLands team

**Comment by tosmartak** [comment]
Hi QLands team,

This is great!

Thank you!!

Regards,
Tosin.
