### ISSUE TITLE
Issues creating repository for a form that has passed through testing

### ISSUE THREAD

**Issue by tosmartak** [qlands/FormShare#71]
Hi Qland team, 

I have this issue creating form that looks good and already used for testing phase. However, while trying to create a repository, I got the following error.

![image](https://github.com/qlands/FormShare/assets/69729533/f5fa8b70-f10f-4822-91df-85afa680dc2b)

The 9 submissions during the testing phase, which I still made available to be merged with the repository now shows zero, even though I am able to download it as csv with the zero submission that it is now showing.

The team is currently on the field collecting data, and was hoping this issue could be rectified.

**Comment by qlands** [comment]
Hi Tosin,

This has been fixed in Stable 2.30.0. We will upgrade the servers on Sunday. 

Thanks for reporting it!
