### ISSUE TITLE
Can't update a Case Creator Form: "Case Date" variable missing from 'Upload new version' form

### ISSUE THREAD

**Issue by bensonik** [qlands/FormShare#73]
Hi Carlos,
The `Upload new version` form is missing a `case date` field therefore new version can't be uploaded. Instead, I have to delete and re-upload. See screenshots:
Cheers!
Benson
1. upload case creator draft
![Screenshot 2023-10-05 at 01 52 23](https://github.com/qlands/FormShare/assets/19645225/001acbbb-208f-4fc1-b8f7-6fe4f585eaea)
2. Upload an update
![Screenshot 2023-10-05 at 02 25 34](https://github.com/qlands/FormShare/assets/19645225/273a3826-54a2-4b18-b1b4-6e4463db66b8)

3. Error due to missing case date specifier, eg. `coll_date`in the test forms
![Screenshot 2023-10-05 at 01 48 47](https://github.com/qlands/FormShare/assets/19645225/5049ebf3-7a1d-4426-9db4-4d777084eab6)

**Comment by qlands** [comment]
Oopsie Daisy! 

This was been fixed in https://github.com/qlands/FormShare/commit/2470003a4bfbd896af61a5f6520fa944a86daaba

Please refresh the page and try again

**Comment by qlands** [comment]
It should be OK now

**Comment by bensonik** [comment]
Done, It works. 
For a moment I was getting 500 error on all the form links, but now is fixed.

Ahsante

**Comment by bensonik** [comment]
Same issue for a case follow up subversion, I can't update the subversion, I can delete and reupload.
![Screenshot 2024-04-30 at 19 57 35](https://github.com/qlands/FormShare/assets/19645225/6a55d6e6-243d-4483-9885-8e10af44c499)

![Screenshot 2024-04-30 at 19 57 59](https://github.com/qlands/FormShare/assets/19645225/7ac75bbb-2de0-49f9-8b82-c242db36ec38)

![Screenshot 2024-04-30 at 19 58 12](https://github.com/qlands/FormShare/assets/19645225/91d1a401-672a-46ce-980f-a645d796348c)

**Comment by qlands** [comment]
Hummm. I thought it was corrected. Can you share the DISA project with me cquiros@qlands.com and give me editor access? This will allowed me to correct this error. You can remove me afterward

**Comment by bensonik** [comment]
The issue before was with case creator form, this was resolved. Now I found similar problem with follow up  form subversion. ( or maybe I should have opened a new issue)

**Comment by qlands** [comment]
Don't worry we will look at it

**Comment by qlands** [comment]
Hi @bensonik . We applied a patch to the code, and you should now be able to update the form. Please let us know if the bug has been corrected

**Comment by bensonik** [comment]
It's been resolved, many thanks!!
