### ISSUE TITLE
Updating Form Files of a deployed Survey

### ISSUE THREAD

**Issue by tosmartak** [qlands/FormShare#75]
A form has been deployed with a repository. This form has form files from which data is pulled, including another one linked to the select_one function. However, while trying to upload an update made to these form files, it gives an error that is blank without specifying what is causing the error. Below is a screen shot.

![image](https://github.com/qlands/FormShare/assets/69729533/07f5fb6c-9809-4898-a3ae-75b97fb7d152)

![image](https://github.com/qlands/FormShare/assets/69729533/df1c8cd6-cfdb-46e5-abb5-88783ddf5987)

![image](https://github.com/qlands/FormShare/assets/69729533/3429f193-85de-48b0-a9b7-f75158514ee4)

I would be glad if this could be looked into. Also, one of the reasons for going through this route, especially for select_one is the flexibility to make changes without having to merge a new form and create a new version or repository.

**Comment by qlands** [comment]
Hi Tosin,

Sorry for the inconvenience,

Would it be possible for you to send the form and associated files (the ones in the server and the new ones that you want to upload) to formshare_support@qlands.com. 

We will check what is the problem.

Thank you

**Comment by tosmartak** [comment]
Hi Qlands,

Please see the form below
[Household Survey Mothers test.xlsx](https://github.com/qlands/FormShare/files/13235417/Household.Survey.Mothers.test.xlsx)

Here are the associated old and new form files that we need to update:
**Old**
[mother_case_search_id.csv](https://github.com/qlands/FormShare/files/13235482/mother_case_search_id.csv)
[mother_case_search_id_pull.csv](https://github.com/qlands/FormShare/files/13235483/mother_case_search_id_pull.csv)

**New**
[mother_case_search_id.csv](https://github.com/qlands/FormShare/files/13235442/mother_case_search_id.csv)
[mother_case_search_id_pull.csv](https://github.com/qlands/FormShare/files/13235444/mother_case_search_id_pull.csv)

**Comment by tosmartak** [comment]
Dear Formshare support,
As requested, please see attached the form and the form files (old and new).
Best regards,Tosin.

    On Wednesday, 1 November 2023 at 22:23:02 GMT+3, QLands ***@***.***> wrote:  
 
 


Hi Tosin,

Sorry for the inconvenience,

Would it be possible for you to send the form and associated files (the ones in the server and the new ones that you want to upload) to ***@***.***

We will check what is the problem.

Thank you

**Comment by qlands** [comment]
Hi Tosin,

Thank you for the files. Which variable did you use to control duplicates? We want to replicate the problem on our local servers.

**Comment by qlands** [comment]
Hi Tosin. We fixed this issue in commits c6aeefd04657a1afba29c45a839cbd5ad2bf7012 and a5e9181bdd3300457dbbe4c7e409837fd76994f7 and available in version 2.30.1 at https://formshare.org. I will update the Alliance server asap.

**Comment by tosmartak** [comment]
Thank you very much.
